name: 'state'

on:
  push:
    branches:
      - main
  pull_request:

env:
  ORGANIZATION_MANAGEMENT_ACCOUNT_ID: ${{ vars.MANAGEMENT_ACCOUNT_ID }}
  COMPANY_IDENTIFIER: goldrock
  WORKING_DIRECTORY: ./state/
  region: us-east-2

concurrency: state

jobs:
  setup:
    name: 'state-exists-check'
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      id-token: write

    outputs:
      bucket_exists: ${{steps.s3bucket.outputs.bucket_exists}}
      key_exists: ${{steps.kmskey.outputs.kms_key_exists}}
      dynamodb_table_exists: ${{steps.dynamodbtable.outputs.dynamodb_table_exists}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:role/${{env.COMPANY_IDENTIFIER}}-github-actions
          aws-region: us-east-2
          mask-aws-account-id: false

      - name: s3bucket
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          if [ ! -z "$( aws s3api head-bucket --bucket ${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}} 2>/dev/null)" ];
          then
            echo BUCKET_EXISTS=true >> "$GITHUB_ENV"
          else
            echo BUCKET_EXISTS=false >> "$GITHUB_ENV"
          fi

      - name: kmskey
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          KEY_EXISTS=false
          KMS_KEY_EXISTS_CHECK=$(aws kms describe-key --key-id arn:aws:kms:us-east-2:${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:alias/${{env.COMPANY_IDENTIFIER}}-tfstate 2>&1)
          KMS_KEY_ACCOUNT=$(echo $KMS_KEY_EXISTS_CHECK | jq -r '.KeyMetadata.AWSAccountId')
          [ $KMS_KEY_ACCOUNT = "${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}" ] && echo KEY_EXISTS=true >> "$GITHUB_ENV" || KEY_EXISTS=false >> "$GITHUB_ENV"

      - name: dynamodbtable
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          DYNAMODB_TABLE_EXISTS=false
          DYNAMODB_TABLE_EXISTS_CHECK=$( aws dynamodb describe-table --table-name arn:aws:dynamodb:${{env.region}}:${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:table/${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}} | jq -r '.Table.TableArn' 2>&1)
          DYNAMODB_ACCOUNT=$(echo $DYNAMODB_TABLE_EXISTS_CHECK | cut -d ":" -f5)
          [ "$DYNAMODB_ACCOUNT" = "${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}" ] && echo DYNAMODB_TABLE_EXISTS=true >> "$GITHUB_ENV" || DYNAMODB_TABLE_EXISTS=false >> "$GITHUB_ENV"

      - name: create bucket
        if: ${{ ! env.BUCKET_EXISTS }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          if [ ${{env.region}} = "us-east-1" ];
          then
            aws s3api create-bucket --bucket ${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-us-east-1
          else
            aws s3api create-bucket --bucket ${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}} --region ${{env.region}} --create-bucket-configuration LocationConstraint=${{env.region}}
          fi

      - name: create key
        if: ${{ ! env.KEY_EXISTS }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          KEY_ID=$(aws kms create-key --multi-region | jq '.KeyMetadata.KeyId')
          aws kms create-alias --alias-name alias/${{env.COMPANY_IDENTIFIER}}-tfstate --target-key-id $KEY_ID

      - name: create dynamodb table
        if: ${{ ! env.DYNAMODB_TABLE_EXISTS }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          aws dynamodb create-table –table-name ${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}} \
          --sse-specification Enabled=true,SSEType=KMS,KMSMasterKeyId=arn:aws:kms:${{env.region}}:${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:alias/${{env.COMPANY_IDENTIFIER}}-tfstate" \
          –attribute-definitions AttributeName=LockID,AttributeType=S –key-schema AttributeName=LockID,KeyType=HASH \ 
          –provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5


      - name: Terraform init
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          terraform init \
            -backend-config="bucket=${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}}" \
            -backend-config="dynamodb_table=arn:aws:dynamodb:${{env.region}}:${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:table/${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}}" \
            -backend-config="kms_key_id=arn:aws:kms:${{env.region}}:${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:alias/${{env.COMPANY_IDENTIFIER}}-tfstate" \
            -backend-config="key=${{env.region}}-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-$GITHUB_WORKFLOW" \
            -backend-config="region=${{env.region}}" \
            -backend-config="encrypt=true"

      - name: Terraform import bucket
        if: ${{ ! env.BUCKET_EXISTS }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          terraform import aws_s3_bucket.bucket ${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}}

      - name: Terraform import kms key
        if: ${{ ! env.KEY_EXISTS }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          terraform import aws_kms_alias.alias alias/${{env.COMPANY_IDENTIFIER}}-tfstate
          terraform import aws_kms_key.key $(aws kms describe-key --key-id arn:aws:kms:${{env.region}}:${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}:alias/${{env.COMPANY_IDENTIFIER}}-tfstate | jq -r '.KeyMetadata.KeyId')
      
      - name: Terraform import dynamodb table
        if: ${{ ! env.DYNAMODB_TABLE_EXISTS }}
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          terraform import aws_dynamodb_table.tf_lock_table ${{env.COMPANY_IDENTIFIER}}-tfstate-${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}-${{env.region}}

      - name: Terraform format check
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: terraform fmt -check

      - name: Terraform plan
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: terraform plan -out plan
        env:
          TF_VAR_management_account_id: ${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}
          TF_VAR_account_id: ${{env.ORGANIZATION_MANAGEMENT_ACCOUNT_ID}}
          TF_VAR_region: ${{env.region}}
          TF_VAR_ref: ${{github.ref_name}}
          TF_VAR_company_identifier: ${{env.COMPANY_IDENTIFIER}}

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: terraform apply plan
